// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Microsoft.AI.Skills.SkillInterface.1.h"
#include "winrt/impl/Windows.Media.1.h"
#include "winrt/impl/Microsoft.AI.Skills.Vision.ConceptTagger.1.h"

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::Vision::ConceptTagger {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::Vision::ConceptTagger {

struct WINRT_EBO ConceptTagScore :
    Microsoft::AI::Skills::Vision::ConceptTagger::IConceptTagScore
{
    ConceptTagScore(std::nullptr_t) noexcept {}
};

struct WINRT_EBO ConceptTaggerBinding :
    Microsoft::AI::Skills::SkillInterface::ISkillBinding,
    impl::require<ConceptTaggerBinding, Microsoft::AI::Skills::Vision::ConceptTagger::IConceptTaggerBinding>
{
    ConceptTaggerBinding(std::nullptr_t) noexcept {}
};

struct WINRT_EBO ConceptTaggerDescriptor :
    Microsoft::AI::Skills::SkillInterface::ISkillDescriptor
{
    ConceptTaggerDescriptor(std::nullptr_t) noexcept {}
    ConceptTaggerDescriptor();
};

struct WINRT_EBO ConceptTaggerSkill :
    Microsoft::AI::Skills::SkillInterface::ISkill
{
    ConceptTaggerSkill(std::nullptr_t) noexcept {}
};

}
