// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Microsoft.AI.Skills.SkillInterface.0.h"
#include "winrt/impl/Windows.Media.0.h"
#include "winrt/impl/Microsoft.AI.Skills.Vision.ConceptTagger.0.h"

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::Vision::ConceptTagger {

struct WINRT_EBO IConceptTagScore :
    Windows::Foundation::IInspectable,
    impl::consume_t<IConceptTagScore>
{
    IConceptTagScore(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IConceptTaggerBinding :
    Windows::Foundation::IInspectable,
    impl::consume_t<IConceptTaggerBinding>
{
    IConceptTaggerBinding(std::nullptr_t = nullptr) noexcept {}
};

}
